[libraries]
commons-io = "commons-io:commons-io:2.11.0"
json-schema-validator = "com.networknt:json-schema-validator:1.0.72"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.2"
mockk = "io.mockk:mockk:1.13.5"
