name: Event Contract CI/CD

on:
  push:
    branches:
      - main
      - version/v*
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build_and_test:
    name: build_and_test
    uses: projectronin/github/.github/workflows/event_contract_cicd_gradle.yaml@main
    secrets:
      nexus_user:      ${{ secrets.NEXUS_MAVEN_USER }}
      nexus_token:     ${{ secrets.NEXUS_MAVEN_TOKEN }}
